apiVersion: v1
kind: Pod
metadata:
 name: dss
spec:
 containers:
  - image: kubernetes/dataset-server
    name: dss
    volumeMounts:
      - name: datasets
        mountPath: /mnt/datasets
 volumes:
      - name: datasets
        azureDisk:
          diskName: test.vhd
          diskURI: https://someaccount.blob.microsoft.net/vhds/test.vhd